services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: always
    platform: linux/amd64
#    platform: linux/arm64/v8
    logging:
              driver: "json-file"
              options:
                  max-size: "1m"
