services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: always
    platform: linux/amd64
    #    platform: linux/arm64/v8
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
  restarter:
    image: docker:cli
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 600; docker restart fastapi-application; done" ]
    restart: unless-stopped
